source 'https://rubygems.org'

gem 'rails', github: "rails/rails"
gem 'sprockets-rails', github: "rails/sprockets-rails"
gem 'sprockets', github: "rails/sprockets"
gem 'sass-rails', github: "rails/sass-rails"
gem 'arel', github: "rails/arel"
gem 'rack', github: "rack/rack"

gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', github: "rails/coffee-rails"

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'bcrypt', '~> 3.1.7'
gem 'will_paginate', github: "jonatack/will_paginate"
gem 'bootstrap-sass', '~> 3.3'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  gem 'byebug'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
end

group :development do
  gem 'web-console', github: 'rails/web-console'
  gem 'spring'
  gem 'mailcatcher'
end

group :test do
  gem 'capybara', github: 'jnicklas/capybara'
  gem 'minitest-rails', github: "pwnall/minitest-rails", branch: "rails5"
  gem 'minitest-rails-capybara', github: "blowmage/minitest-rails-capybara", branch: "rails5"
  gem 'capybara-webkit'
  gem 'poltergeist'
end
