source 'https://rubygems.org'

gem 'rails', '5.0.0.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'bcrypt', '~> 3.1'
gem 'cancan'

gem 'web-console', '~> 3.0', group: :development

group :development, :test do
  gem 'byebug'
  gem 'spring'
end

group :test do
  gem 'minitest-rails'
end
